/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiEvalRouteImport } from './routes/api/eval'
import { Route as ApiKeysRouteImport } from './routes/api/keys'
import { Route as ApiLabRouteImport } from './routes/api/lab'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as SourcesSlugRouteImport } from './routes/sources.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEvalRoute = ApiEvalRouteImport.update({
  id: '/api/eval',
  path: '/api/eval',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiKeysRoute = ApiKeysRouteImport.update({
  id: '/api/keys',
  path: '/api/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabRoute = ApiLabRouteImport.update({
  id: '/api/lab',
  path: '/api/lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const SourcesSlugRoute = SourcesSlugRouteImport.update({
  id: '/sources/$slug',
  path: '/sources/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/eval': typeof ApiEvalRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/lab': typeof ApiLabRoute
  '/api/query': typeof ApiQueryRoute
  '/sources/$slug': typeof SourcesSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/eval': typeof ApiEvalRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/lab': typeof ApiLabRoute
  '/api/query': typeof ApiQueryRoute
  '/sources/$slug': typeof SourcesSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/eval': typeof ApiEvalRoute
  '/api/keys': typeof ApiKeysRoute
  '/api/lab': typeof ApiLabRoute
  '/api/query': typeof ApiQueryRoute
  '/sources/$slug': typeof SourcesSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/eval'
    | '/api/keys'
    | '/api/lab'
    | '/api/query'
    | '/sources/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/eval'
    | '/api/keys'
    | '/api/lab'
    | '/api/query'
    | '/sources/$slug'
  id:
    | '__root__'
    | '/'
    | '/api/eval'
    | '/api/keys'
    | '/api/lab'
    | '/api/query'
    | '/sources/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiEvalRoute: typeof ApiEvalRoute
  ApiKeysRoute: typeof ApiKeysRoute
  ApiLabRoute: typeof ApiLabRoute
  ApiQueryRoute: typeof ApiQueryRoute
  SourcesSlugRoute: typeof SourcesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/eval': {
      id: '/api/eval'
      path: '/api/eval'
      fullPath: '/api/eval'
      preLoaderRoute: typeof ApiEvalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/keys': {
      id: '/api/keys'
      path: '/api/keys'
      fullPath: '/api/keys'
      preLoaderRoute: typeof ApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lab': {
      id: '/api/lab'
      path: '/api/lab'
      fullPath: '/api/lab'
      preLoaderRoute: typeof ApiLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sources/$slug': {
      id: '/sources/$slug'
      path: '/sources/$slug'
      fullPath: '/sources/$slug'
      preLoaderRoute: typeof SourcesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiEvalRoute: ApiEvalRoute,
  ApiKeysRoute: ApiKeysRoute,
  ApiLabRoute: ApiLabRoute,
  ApiQueryRoute: ApiQueryRoute,
  SourcesSlugRoute: SourcesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
